### ISSUE TITLE
Error disabling default configmaps

### ISSUE THREAD

**Issue by ahoulgrave** [kiwigrid/helm-charts#107]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
```shell
$ helm version
```
```                                                                                                                                 
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

```shell
$ kubectl version
```
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart in which version**:

```shell
$ helm search kiwigrid/fluentd-elasticsearch
```
```
NAME                            CHART VERSION   APP VERSION     DESCRIPTION                                                 
kiwigrid/fluentd-elasticsearch  2.9.1           2.5.1           A Fluentd Helm chart for Kubernetes with Elasticsearch ou...
```

**What happened**:
Following your [values.yml](https://github.com/kiwigrid/helm-charts/blob/master/charts/fluentd-elasticsearch/values.yaml) file, i copy pasted the following part:

```yaml
configMaps:
  useDefaults:
    systemConf: false
extraConfigMaps:
  system.conf: |-
    <system>
      root_dir /tmp/fluentd-buffers/
      <log>
        format json
      </log>
    </system>
```

When i try to apply changes, it complains:

> Error: UPGRADE FAILED: render error in "fluentd-elasticsearch/templates/daemonset.yaml": template: fluentd-elasticsearch/templates/daemonset.yaml:40:28: executing "fluentd-elasticsearch/templates/daemonset.yaml" at <include (print $.Tem...>: error calling include: template: fluentd-elasticsearch/templates/configmap.yaml:15:19: executing "fluentd-elasticsearch/templates/configmap.yaml" at <4>: wrong type for value; expected string; got map[string]interface {}

Following your readme as well, i used
```yaml
configMaps.useDefaults.systemConf: false
extraConfigMaps:
  system.conf: |-
    <system>
      root_dir /tmp/fluentd-buffers/
      <log>
        format json
      </log>
    </system>
```

With this setting, it does not complain, but the default system conf is added anyway, and my custom configmap is ignored.

**What you expected to happen**:
Generated yamls would not add the default system.conf configmap and add my custom system.conf configmap.

**How to reproduce it** (as minimally and precisely as possible):
Create a values.yaml file with this content:

```yaml
configMaps:
  useDefaults:
    systemConf: true
    containersInputConf: true
    systemInputConf: true
    forwardInputConf: true
    monitoringConf: true
    outputConf: true
```

Run this:
```shell
helm upgrade --dry-run --debug --install -f values.yaml fluentd kiwigrid/fluentd-elastics
earch
```

**Anything else we need to know**:

**Comment by monotek** [comment]
Works for me.
System.conf is added to the end of the configmaps.

Used a values file which looked like this:

```
configMaps:
  useDefaults:
    systemConf: false
    containersInputConf: true
    systemInputConf: true
    forwardInputConf: true
    monitoringConf: true
    outputConf: true

# can be used to add new config or overwrite the default configmaps completely after the configmaps default has been disabled above
extraConfigMaps:
  system.conf: |-
    <system>
      root_dir /tmp/fluentd-buffers/
    </system>
```
