### ISSUE TITLE
Prometheus Thanos: Allow --objstore.config-file to be used

### ISSUE THREAD

**Issue by Smirl** [kiwigrid/helm-charts#164]
## Promlem

At the moment `--objstore.config` is defined inline in the Store Gateway, Compact, and Ruler with:

- `storeGateway.objStoreConfig`
- `ruler.objStoreConfig`
- `compact.objStoreConfig`

This requires the `values.yaml` to contain secrets, and to be repeated many times.

## Feature Request

To be able to specify a secret out of the helm chart (perhaps in the helm chart too?) which can be referenced in the values file for each component.

## Implementation Options

1. The helm chart already supports mounting volumes. So secrets could be mounted, and the object-file argument point at the mounted path.
2. The secret could be mounted as an environment variable and `--objstore.object` used with the value of the variable, similar to that of `prometheus-operator` thanos sidecar. See https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/statefulset.go#L705

## Next Steps

I will raise a PR with option 1 above as I think it is the best suited for this helm chart. Comments are appreciated.

**Comment by Smirl** [comment]
Looking closer, it is possible to use a combination of `additionalFlags`, `volumeMounts`, and `volumes` to achieve this. Therefore I will hold off on the PR if you think it would be adding too much complexity to the chart?

Currently I have something like:

```diff
--- a/charts/prometheus-thanos/templates/compact-deployment.yaml
+++ b/charts/prometheus-thanos/templates/compact-deployment.yaml
@@ -51,6 +51,8 @@ spec:
             --objstore.config=type: {{ .Values.compact.objStoreType }}
             config:
             {{- toYaml .Values.compact.objStoreConfig | nindent 14 }}
+          {{ else if .Values.compact.objStoreConfigFile }}
+          - --objstore.config-file={{ .Values.compact.objStoreConfigFile }}
           {{- end }}
           - --wait
           ports:
```

**Comment by Smirl** [comment]
As per above comment. I think it should be possible with something like:
```yaml
  additionalFlags:
    objstore.config-file: /opt/thanos-objstore-config/bucket.yaml
  volumes:
  - name: thanos-objstore-config
    secret:
      secretName: thanos-objstore-config
  volumeMounts:
  - name: thanos-objstore-config
    mountPath: /opt/thanos-objstore-config/
    readOnly: true
```
