### ISSUE TITLE
where is sidecar component

### ISSUE THREAD

**Issue by kapilgarg83** [kiwigrid/helm-charts#184]
Hi,
Where is sidecar compoenent in it.

I have running Prometheus server that is deployed using helm.
Now I want to implement thnos separately without changing Prometheus setup.

please suggest

**Comment by axdotl** [comment]
Hi @kapilgarg83,

I'm not sure that I got you right.
Did you already check our thanos Helm chart? https://github.com/kiwigrid/helm-charts/tree/master/charts/prometheus-thanos

Once you setup Thanos with mentioned Helm chart, you only have to add the thanos sidecar to your prometheus server via values.yaml, something like this:
```yaml
server:
  sidecarContainers:
        - name: thanos
      image: quay.io/thanos/thanos:v0.7.0
      args:
        - sidecar
        - --log.level=info
        - --tsdb.path=/var/prometheus
        - --prometheus.url=http://localhost:9090
```

Hope this helps, feel free to re-open the issue if this was not sufficient.
