### ISSUE TITLE
ES indices not created and returning warning - ES Detected ES 7.x or above: `_doc` will be used as the document `_type`

### ISSUE THREAD

**Issue by mapdegree** [kiwigrid/helm-charts#363]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report.

**Version of Helm and Kubernetes**:
v3.2.1, K8S 1.14

**Which chart in which version**:
fluentd-elasticsearch 9.3.1

**What happened**:
FluentD does not create the ES index and returning following warning every couple of miliseconds

elasticsearch Detected ES 7.x or above: `_doc` will be used as the document `_type`

**What you expected to happen**:
ES index created

**How to reproduce it** (as minimally and precisely as possible):
We use ECK in K8S on AWS.

This is the configuration stake we use:
```
elasticsearch:
  auth:
    enabled: true
    user: 'elastic'
    password: '***'
  hosts:
    - '***.***.svc:9200'
  scheme: 'https'
  sslVerify: false
  ssl_version: TLSv1_2
  buffer_chunk_limit: 4M
  buffer_queue_limit: 16
  reloadOnFailure: true
  reloadConnections: true
  logstash_prefix: 'test-'
```

**Anything else we need to know**:
fluentd runs in the same K8S namespace as the ES cluster of the ECK.

We read that this issue does not occur on newer images of FluentD.
Source:
https://github.com/helm/charts/issues/16588
