### ISSUE TITLE
FEATURE REQUEST - Configurable of Container Input from Helm Chart

### ISSUE THREAD

**Issue by tschaible** [kiwigrid/helm-charts#387]
**Is this a request for help?**:  No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm 3.1.2, Kubernetes 1.15

**Which chart in which version**:
fluentd-elasticsearch 9.6.0

**What happened**:
I would like to configure 2 aspects of the processing of container logs
 * I want to turn off the multi-line aggregation (but leave exception detection)
 * I want to turn retain the original log field when parsing json logs outputted but k8s containers

I had to completely re-include the container-input section with my own customizations

**What you expected to happen**:
I was hoping to perform a simple configuration with helm values

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
I would propose allowing for the following settings

```
containerLogs:
  detectExceptions: 
    enabled: true
  multiLineLogs:
    enabled: true
  parseJson:
    enabled: true
    removeKeyName: true
```

this would allow for future expansion of the configurability
