### ISSUE TITLE
[fluentd-elasticsearch] How to use Fluentd with Elastic's chart using authentication?

### ISSUE THREAD

**Issue by AsterYujano** [kiwigrid/helm-charts#392]
**Is this a request for help?**: **Yes**

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Not sure

**Version of Helm and Kubernetes**:
Kubernetes: 1.18.6
Helm: 3.2.1

**Which chart in which version**:
helm-es-security: 7.8.1 (https://github.com/elastic/helm-charts/tree/7.8.1/elasticsearch/examples/security)
Fluentd: 9.6.0  (This repository)

**What happened**:
Fluentd logs: `Could not communicate to Elasticsearch, resetting connection and trying again. end of file reached (EOFError)`

**What you expected to happen**:
Working with ES and authentication

**How to reproduce it** (as minimally and precisely as possible):
1) Install https://github.com/elastic/helm-charts/tree/7.8.1/elasticsearch/examples/security with "make secrets" and "make install". I replaced the make install command with `helm install --values ./security.yml helm-es-security --version 7.8.1 ../../`

2) test ES is working with port forward and `curl -k -u elastic:YOUR_PASS_IN_THE_K8S_SECRET https://localhost:9200`

3) install fluentd chart with these changes in values.yml:

```
elasticsearch:
  auth:
    enabled: true
    user: "elastic"
    password: "YOUR_PASS_IN_THE_K8S_SECRET"

  hosts: ["security-master:9200"]
```

4) iinspect Fluentd logs: `Could not communicate to Elasticsearch, resetting connection and trying again. end of file reached (EOFError)`

**Anything else we need to know**:

I am trying to set-up Kibana with auth. Therefore I need ES to work, so I need Fluentd to connect to ElasticSearch with authentication.

---

What I tried, but same error

Adding this secret in the yml:
```
secret:
 - name: ELASTICSEARCH_PASSWORD
   secret_name: elastic-credentials
   secret_key: password
```

Best,

**Comment by monotek** [comment]
Just put in user and password. 

```
elasticsearch:
  auth:
    enabled: true
    user: "user"
    password: "pass"
```

https://github.com/kiwigrid/helm-charts/blob/master/charts/fluentd-elasticsearch/templates/configmaps.yaml#L510-L513
https://github.com/kiwigrid/helm-charts/blob/master/charts/fluentd-elasticsearch/templates/daemonset.yaml#L76-L81

If you want to use a exisitng secret, bey referencing it, use:

```
secret:
 - name: ELASTICSEARCH_PASSWORD
   secret_name: elastic-credentials
   secret_key: password
```

Not both.

Just check the created configmap, and env vars, to see if evrything is configured right.
