### ISSUE TITLE
grafana_dashboard=1 not working 

### ISSUE THREAD

**Issue by gowrisankar22** [kiwigrid/helm-charts#433]
If I want to deploy additional Grafana dashboards, the recommendation says that, to add a ConfigMap or Secret which has a label grafana_dashboard=1. The ConfigMap or Secret does not have to be in the same namespace monitoring but this works, if deployed in the same namespace. Not sure what I am missing

```
 sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
```
